- type: entity
  name: mango
  parent: FoodProduceBase
  id: FoodMango
  description: "MANGO MANGO MANGO"
  components:
  - type: FlavorProfile
    flavors:
      - sweet
      - fruity
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 9
        reagents:
        - ReagentId: Nutriment
          Quantity: 4
        - ReagentId: Vitamin
          Quantity: 5
  - type: Sprite
    sprite: _RMC14/Objects/Kitchen/Plants/mango.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: mango
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceMango
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  - type: FoodSequenceElement
    # TODO: Sequence sprites are to be scaled by 0.8x.
    entries:
      Taco: MangoTaco
      Burger: MangoBurger

- type: foodSequenceElement
  id: MangoTaco
  name: food-sequence-content-mango
  scale: 0.8,0.8
  sprites:
  - sprite: _RMC14/Objects/Kitchen/Plants/mango.rsi
    state: produce

- type: foodSequenceElement
  id: MangoBurger
  name: food-sequence-burger-content-mango
  scale: 0.8,0.8
  sprites:
  - sprite: _RMC14/Objects/Kitchen/Plants/mango.rsi
    state: produce
