# SPDX-FileCopyrightText: 2022 Checkraze <71046427+Cheackraze@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ubaser <134914314+UbaserB@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: parallax
  id: TrainStation
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxBG.png"
      slowness: 0.978046875
      scrolling: "0, -0.578046875"
      scale: "1, 1"
      tiled: false
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/Asteroids.png"
      slowness: 0.968046875
      scrolling: "0, -0.568046875"
      scale: "1.3, 1.3"
      worldHomePosition: "-624, 333"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/AspidParallaxNeb.png"
      slowness: 0.969046875
      scrolling: "0, -0.569046875"
      scale: "0.5, 0.5"
      worldHomePosition: "0, 0"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/Parallaxes/Asteroids.png"
      slowness: 0.938046875
      scrolling: "0, -0.708046875"
      scale: "1, 1"
  layersLQ:
    - texture:
        !type:GeneratedParallaxTextureSource
        id: ""
        configPath: "/Prototypes/Parallaxes/parallax_config.toml"
      slowness: 0.875
      scrolling: "0, -0.475"
  layersLQUseHQ: false